# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ciut IRC AllNetwork Indonesia
stitle: ciut AllNetwork
email: ciutirc@gmail.com
img: https://user-images.githubusercontent.com/8485824/34022380-7dc915d0-e171-11e7-89b1-b4b3d5913276.jpg
description: > # this means to ignore newlines until "baseurl:"
  Channel ciut di ambil dari kata jawa yang berarti sempit. #ciut berdiri pada pertengahan Novermber 2009 yang di founderi oleh nick bgz & syaf. Walau dibilang sempit namun nyatanya #ciut adalah channel yang tidak kalah dengan chan lain nya, karena ciuter'z sangat banyak, walau umumnya kawasan jember dan jawa timur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ciut.github.io" # the base hostname & protocol for your site
permalink: /:title/
twitter_username: eggoez
github_username:  eggoez

# Build settings
markdown: kramdown
