#!/bin/bash
budal="y";
wurung="t";
read -p "Commit n Push?? (y/t)? : " pie
if [ $pie == $wurung ]; then
echo ""
else
echo -n "Pesan Commit? : "
read pesan
echo ""
echo -e "\033[30;43;4mJangan lupa login akun!\033[0m"
git add *
git add .*
git commit -a -m "$pesan"
git push --all
fi
echo -e "\e[45msh powered by bagus18\e[0m" 

